export const SCHOOL_TO_STATE: Record<string, string> = {
  "Abilene Christian": "TX",
  "Air Force": "CO",
  "Akron": "OH",
  "Ala-Birmingham": "AL",
  "Alabama": "AL",
  "Alabama A&M": "AL",
  "Alabama St.": "AL",
  "Albany (NY)": "NY",
  "Albany State (GA)": "GA",
  "Albion": "MI",
  "Appalachian St.": "NC",
  "Arizona": "AZ",
  "Arizona St.": "AZ",
  "Ark-Pine Bluff": "AR",
  "Arkansas": "AR",
  "Arkansas St.": "AR",
  "Arkansas–Monticello": "AR",
  "Army": "NY",
  "Ashland": "OH",
  "Auburn": "AL",
  "BYU": "UT",
  "Ball St.": "IN",
  "Baylor": "TX",
  "Bethune-Cookman": "FL",
  "Bloomsburg": "PA",
  "Boise St.": "ID",
  "Boston Col.": "MA",
  "Bowling Green": "OH",
  "Brown": "RI",
  "Buffalo": "NY",
  "Cal Poly-San Luis Obispo": "CA",
  "California": "CA",
  "Carson-Newman": "TN",
  "Central Arkansas": "AR",
  "Central Connecticut St.": "CT",
  "Central Florida": "FL",
  "Central Michigan": "MI",
  "Central Missouri St.": "MO",
  "Charleston (WV)": "WV",
  "Charlotte": "NC",
  "Chattanooga": "TN",
  "Cincinnati": "OH",
  "Clemson": "SC",
  "Coastal Carolina": "SC",
  "Colorado": "CO",
  "Colorado St.": "CO",
  "Concordia-St.Paul (MN)": "MN",
  "Connecticut": "CT",
  "Dartmouth": "NH",
  "Dayton": "OH",
  "Delaware": "DE",
  "Delaware St.": "DE",
  "Delta St.": "MS",
  "Drake": "IA",
  "Duke": "NC",
  "East Carolina": "NC",
  "East Central (OK)": "OK",
  "Eastern Illinois": "IL",
  "Eastern Kentucky": "KY",
  "Eastern Michigan": "MI",
  "Eastern Washington": "WA",
  "Elon": "NC",
  "Fayetteville St.": "NC",
  "Ferris St.": "MI",
  "Florida": "FL",
  "Florida A&M": "FL",
  "Florida Atlantic": "FL",
  "Florida International": "FL",
  "Florida St.": "FL",
  "Fordham": "NY",
  "Fort Hays St.": "KS",
  "Fresno St.": "CA",
  "Furman": "SC",
  "Gardner-Webb": "NC",
  "Georgia": "GA",
  "Georgia Southern": "GA",
  "Georgia St.": "GA",
  "Georgia Tech": "GA",
  "Grambling St.": "LA",
  "Grand Valley St.": "MI",
  "Gustavus Adolphus": "MN",
  "Hampton": "VA",
  "Harvard": "MA",
  "Hawaii": "HI",
  "Hinds CC": "MS",
  "Hofstra": "NY",
  "Houston": "TX",
  "Houston Christian": "TX",
  "Howard": "DC",
  "Idaho": "ID",
  "Idaho St.": "ID",
  "Illinois": "IL",
  "Illinois St.": "IL",
  "Indiana": "IN",
  "Indiana (PA)": "PA",
  "Iowa": "IA",
  "Iowa St.": "IA",
  "Jackson St.": "MS",
  "Jacksonville St.": "AL",
  "James Madison": "VA",
  "Kansas": "KS",
  "Kansas St.": "KS",
  "Kennesaw St.": "GA",
  "Kent St.": "OH",
  "Kentucky": "KY",
  "Kentucky St.": "KY",
  "LSU": "LA",
  "La-Monroe": "LA",
  "Lamar": "TX",
  "Lambuth": "TN",
  "Lane": "TN",
  "Lenoir-Rhyne": "NC",
  "Liberty": "VA",
  "Lindenwood": "MO",
  "Long Beach CC": "CA",
  "Louisiana": "LA",
  "Louisiana Tech": "LA",
  "Louisville": "KY",
  "Maine": "ME",
  "Manitoba": "INT",
  "Marist": "NY",
  "Mars Hill": "NC",
  "Marshall": "WV",
  "Maryland": "MD",
  "Massachusetts": "MA",
  "McGill": "INT",
  "McNeese St.": "LA",
  "Memphis": "TN",
  "Miami (FL)": "FL",
  "Miami (OH)": "OH",
  "Michigan": "MI",
  "Michigan St.": "MI",
  "Middle Tenn. St.": "TN",
  "Midwestern St.": "TX",
  "Minnesota": "MN",
  "Mississippi": "MS",
  "Mississippi St.": "MS",
  "Missouri": "MO",
  "Missouri Southern": "MO",
  "Missouri State": "MO",
  "Missouri Western St.": "MO",
  "Monmouth": "NJ",
  "Montana": "MT",
  "Montana St.": "MT",
  "Morgan St.": "MD",
  "Mount Union": "OH",
  "Murray St.": "KY",
  "NW Missouri St.": "MO",
  "NW Oklahoma St.": "OK",
  "Navy": "MD",
  "Nebraska": "NE",
  "Nebraska-Omaha": "NE",
  "Nevada": "NV",
  "New Hampshire": "NH",
  "New Mexico": "NM",
  "New Mexico St.": "NM",
  "Newberry": "SC",
  "Nicholls St.": "LA",
  "Norfolk St.": "VA",
  "North Alabama": "AL",
  "North Carolina": "NC",
  "North Carolina A&T": "NC",
  "North Carolina Central": "NC",
  "North Carolina St.": "NC",
  "North Dakota St.": "ND",
  "North Texas": "TX",
  "Northern Arizona": "AZ",
  "Northern Colorado": "CO",
  "Northern Illinois": "IL",
  "Northern Iowa": "IA",
  "Northwestern": "IL",
  "Northwestern St. (LA)": "LA",
  "Notre Dame": "IN",
  "Ohio": "OH",
  "Ohio St.": "OH",
  "Oklahoma": "OK",
  "Oklahoma St.": "OK",
  "Old Dominion": "VA",
  "Oregon": "OR",
  "Oregon St.": "OR",
  "Ottawa (KS)": "KS",
  "Ouachita Baptist": "AR",
  "Pearl River CC": "MS",
  "Penn St.": "PA",
  "Pennsylvania": "PA",
  "Pittsburg St.": "KS",
  "Pittsburgh": "PA",
  "Portland St.": "OR",
  "Prairie View A&M": "TX",
  "Presbyterian": "SC",
  "Princeton": "NJ",
  "Purdue": "IN",
  "Regina": "INT",
  "Rice": "TX",
  "Richmond": "VA",
  "Rowan": "NJ",
  "Rutgers": "NJ",
  "S.F. Austin": "TX",
  "SE Missouri St.": "MO",
  "SMU": "TX",
  "Sacramento St.": "CA",
  "Sacred Heart": "CT",
  "Saginaw Valley St.": "MI",
  "Sam Houston St.": "TX",
  "Samford": "AL",
  "San Diego": "CA",
  "San Diego St.": "CA",
  "San Jose St.": "CA",
  "South Alabama": "AL",
  "South Carolina": "SC",
  "South Carolina St.": "SC",
  "South Dakota": "SD",
  "South Dakota St.": "SD",
  "South Florida": "FL",
  "Southeastern Louisiana": "LA",
  "Southern": "LA",
  "Southern Illinois": "IL",
  "Southern Miss": "MS",
  "Southern Utah": "UT",
  "St. Augustine's": "NC",
  "St. Paul's": "VA",
  "Stanford": "CA",
  "Stillman": "AL",
  "Syracuse": "NY",
  "TCU": "TX",
  "Tarleton St.": "TX",
  "Temple": "PA",
  "Tennessee": "TN",
  "Tennessee St.": "TN",
  "Texas": "TX",
  "Texas A&M": "TX",
  "Texas A&M-Commerce": "TX",
  "Texas A&M-Kingsville": "TX",
  "Texas Southern": "TX",
  "Texas St.": "TX",
  "Texas Tech": "TX",
  "Texas-El Paso": "TX",
  "Texas-San Antonio": "TX",
  "The Citadel": "SC",
  "Toledo": "OH",
  "Towson": "MD",
  "Troy": "AL",
  "Tulane": "LA",
  "Tulsa": "OK",
  "Tusculum": "TN",
  "Tuskegee": "AL",
  "UC Davis": "CA",
  "UCLA": "CA",
  "UNLV": "NV",
  "USC": "CA",
  "UT Martin": "TN",
  "Utah": "UT",
  "Utah St.": "UT",
  "Valdosta St.": "GA",
  "Vanderbilt": "TN",
  "Villanova": "PA",
  "Virginia": "VA",
  "Virginia Tech": "VA",
  "Virginia Union": "VA",
  "Wagner": "NY",
  "Wake Forest": "NC",
  "Washburn": "KS",
  "Washington": "WA",
  "Washington St.": "WA",
  "Weber St.": "UT",
  "West Alabama": "AL",
  "West Georgia": "GA",
  "West Texas A&M": "TX",
  "West Virginia": "WV",
  "Western Carolina": "NC",
  "Western Illinois": "IL",
  "Western Kentucky": "KY",
  "Western Michigan": "MI",
  "Western New Mexico": "NM",
  "Western Ontario": "INT",
  "Western Oregon": "OR",
  "Wheaton": "IL",
  "Whitworth": "WA",
  "Widener": "PA",
  "William & Mary": "VA",
  "William Penn": "IA",
  "Wingate": "NC",
  "Winston-Salem St.": "NC",
  "Wisconsin": "WI",
  "Wisconsin–Stout": "WI",
  "Wyoming": "WY",
  "Yale": "CT",
  "Youngstown St.": "OH"
};

export const ALL_STATES = Array.from(new Set(Object.values(SCHOOL_TO_STATE))).sort();
